// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Dados complementares do Cliente (consumidor final).
/// </summary>
public partial class Clientes
{
    public Guid Id { get; set; }

    public Guid UsuarioId { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    /// <summary>
    /// Saldo atual de pontos do cliente (ganhos - resgates).
    /// </summary>
    public int TotalPontos { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();

    public virtual ICollection<ExtratoPontos> ExtratoPontos { get; set; } = new List<ExtratoPontos>();

    public virtual Usuarios Usuario { get; set; }
}