// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Lançamentos de compras feitas por clientes na loja.
/// </summary>
public partial class Compras
{
    public Guid Id { get; set; }

    public Guid ClienteId { get; set; }

    public Guid ParceiroId { get; set; }

    /// <summary>
    /// Funcionário ou Administrador que lançou a compra.
    /// </summary>
    public Guid RegistradoPor { get; set; }

    public decimal Valor { get; set; }

    /// <summary>
    /// Número do cupom fiscal (opcional).
    /// </summary>
    public string NumeroCupom { get; set; }

    public DateTime DataCompra { get; set; }

    /// <summary>
    /// Pontos gerados para o parceiro nesta compra.
    /// </summary>
    public int PontosGeradosParceiro { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    /// <summary>
    /// Pontos gerados para o cliente nesta compra.
    /// </summary>
    public int PontosGeradosCliente { get; set; }

    public virtual Clientes Cliente { get; set; }

    public virtual ICollection<ExtratoPontos> ExtratoPontos { get; set; } = new List<ExtratoPontos>();

    public virtual Parceiros Parceiro { get; set; }

    public virtual Usuarios RegistradoPorNavigation { get; set; }
}