// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Registro de compras internas realizadas por funcionários (apenas para controle, sem gerar pontos).
/// </summary>
public partial class ComprasFuncionarios
{
    public Guid Id { get; set; }

    public Guid FuncionarioId { get; set; }

    /// <summary>
    /// Usuário (Admin ou Funcionario) que registrou a compra.
    /// </summary>
    public Guid RegistradoPor { get; set; }

    /// <summary>
    /// Valor total da compra.
    /// </summary>
    public decimal Valor { get; set; }

    /// <summary>
    /// Descrição opcional dos itens comprados.
    /// </summary>
    public string Descricao { get; set; }

    public DateTime DataCompra { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public virtual Funcionarios Funcionario { get; set; }

    public virtual Usuarios RegistradoPorNavigation { get; set; }
}