// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Ledger imutável — registra toda movimentação de pontos (geração e resgate).
/// </summary>
public partial class ExtratoPontos
{
    public Guid Id { get; set; }

    public Guid ParceiroId { get; set; }

    public int Pontos { get; set; }

    /// <summary>
    /// Valor em R$ equivalente aos pontos (para resgates).
    /// </summary>
    public decimal? ValorMonetario { get; set; }

    /// <summary>
    /// Compra que originou os pontos (NULL para resgates).
    /// </summary>
    public Guid? CompraId { get; set; }

    public string Descricao { get; set; }

    public DateTime CriadoEm { get; set; }

    public virtual Compras Compra { get; set; }

    public virtual Parceiros Parceiro { get; set; }
}