// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

public partial class FaixasPontuacao
{
    public Guid Id { get; set; }

    public Guid RegraPontuacaoId { get; set; }

    public decimal ValorVendas { get; set; }

    public int Pontos { get; set; }

    public DateTime CriadoEm { get; set; }

    public virtual RegrasPontuacao RegraPontuacao { get; set; }
}