// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Regras parametrizáveis de geração de pontos (configuradas pelo Administrador).
/// </summary>
public partial class RegrasPontuacao
{
    public Guid Id { get; set; }

    public string Nome { get; set; }

    /// <summary>
    /// Valor em R$ de compras necessário para gerar pontos (ex: R$ 1.000,00).
    /// </summary>
    public decimal ValorCompraMinimo { get; set; }

    /// <summary>
    /// Quantidade de pontos gerados ao atingir o valor mínimo (ex: 100 pontos).
    /// </summary>
    public int PontosPorValor { get; set; }

    /// <summary>
    /// Valor em R$ que o parceiro recebe ao resgatar pontos (ex: R$ 50,00).
    /// </summary>
    public decimal ValorMonetarioPorPontos { get; set; }

    /// <summary>
    /// Quantidade de pontos necessários para conversão monetária (ex: 100 pontos).
    /// </summary>
    public int PontosParaConversaoMonetaria { get; set; }

    /// <summary>
    /// Apenas uma regra ativa por vez — controlado por lógica de aplicação.
    /// </summary>
    public bool Ativo { get; set; }

    public Guid CriadoPor { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public virtual Usuarios CriadoPorNavigation { get; set; }
}