// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Solicitações de resgate de bônus pelos parceiros.
/// </summary>
public partial class Resgates
{
    public Guid Id { get; set; }

    public Guid ParceiroId { get; set; }

    public int PontosResgatados { get; set; }

    public decimal ValorMonetario { get; set; }

    /// <summary>
    /// Administrador/Funcionário que aprovou o resgate.
    /// </summary>
    public Guid? AprovadoPor { get; set; }

    public string Observacoes { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public virtual Usuarios AprovadoPorNavigation { get; set; }

    public virtual Parceiros Parceiro { get; set; }
}