// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Tokens de refresh para renovação da autenticação JWT.
/// </summary>
public partial class TokensAtualizacao
{
    public Guid Id { get; set; }

    public Guid UsuarioId { get; set; }

    public string Token { get; set; }

    public DateTime ExpiraEm { get; set; }

    /// <summary>
    /// Data/hora da revogação — NULL enquanto ativo.
    /// </summary>
    public DateTime? RevogadoEm { get; set; }

    public DateTime CriadoEm { get; set; }

    public virtual Usuarios Usuario { get; set; }
}