// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RevitaParceiros.Domain.Entities;

/// <summary>
/// Tabela unificada de usuários do sistema (Administrador, Funcionario, Parceiro, Cliente).
/// </summary>
public partial class Usuarios
{
    public Guid Id { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    /// <summary>
    /// Telefone/WhatsApp do usuário.
    /// </summary>
    public string Telefone { get; set; }


    /// <summary>
    /// Hash da senha gerado via bcrypt/Argon2.
    /// </summary>
    public string SenhaHash { get; set; }

    public bool Ativo { get; set; }

    public DateTime CriadoEm { get; set; }

    public DateTime? AtualizadoEm { get; set; }

    public virtual Clientes Clientes { get; set; }

    public virtual ICollection<Compras> Compras { get; set; } = new List<Compras>();

    public virtual Funcionarios Funcionarios { get; set; }

    public virtual Parceiros Parceiros { get; set; }

    public virtual ICollection<RegrasPontuacao> RegrasPontuacao { get; set; } = new List<RegrasPontuacao>();

    public virtual ICollection<Resgates> Resgates { get; set; } = new List<Resgates>();

    public virtual ICollection<TokensAtualizacao> TokensAtualizacao { get; set; } = new List<TokensAtualizacao>();
}