// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using RevitaParceiros.Domain.Entities;

namespace RevitaParceiros.Infra.Persistence;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Compras> Compras { get; set; }

    public virtual DbSet<ComprasFuncionarios> ComprasFuncionarios { get; set; }

    public virtual DbSet<ExtratoPontos> ExtratoPontos { get; set; }

    public virtual DbSet<Funcionarios> Funcionarios { get; set; }

    public virtual DbSet<Parceiros> Parceiros { get; set; }

    public virtual DbSet<RegrasPontuacao> RegrasPontuacao { get; set; }

    public virtual DbSet<Resgates> Resgates { get; set; }

    public virtual DbSet<TokensAtualizacao> TokensAtualizacao { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("pgcrypto")
            .HasPostgresExtension("uuid-ossp");

        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("clientes_pkey");

            entity.ToTable("clientes", tb => tb.HasComment("Dados complementares do Cliente (consumidor final)."));

            entity.HasIndex(e => e.UsuarioId, "uq_clientes_usuario").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.TotalPontos)
                .HasComment("Saldo atual de pontos do cliente (ganhos - resgates).")
                .HasColumnName("total_pontos");
            entity.Property(e => e.UsuarioId).HasColumnName("usuario_id");

            entity.HasOne(d => d.Usuario).WithOne(p => p.Clientes)
                .HasForeignKey<Clientes>(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_clientes_usuario");
        });

        modelBuilder.Entity<Compras>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("compras_pkey");

            entity.ToTable("compras", tb => tb.HasComment("Lançamentos de compras feitas por clientes na loja."));

            entity.HasIndex(e => e.ClienteId, "ix_compras_cliente");

            entity.HasIndex(e => e.DataCompra, "ix_compras_data_compra").IsDescending();

            entity.HasIndex(e => e.ParceiroId, "ix_compras_parceiro");

            entity.HasIndex(e => e.RegistradoPor, "ix_compras_registrado_por");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.ClienteId).HasColumnName("cliente_id");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.DataCompra)
                .HasDefaultValueSql("now()")
                .HasColumnName("data_compra");
            entity.Property(e => e.NumeroCupom)
                .HasMaxLength(50)
                .HasComment("Número do cupom fiscal (opcional).")
                .HasColumnName("numero_cupom");
            entity.Property(e => e.ParceiroId).HasColumnName("parceiro_id");
            entity.Property(e => e.PontosGeradosCliente)
                .HasComment("Pontos gerados para o cliente nesta compra.")
                .HasColumnName("pontos_gerados_cliente");
            entity.Property(e => e.PontosGeradosParceiro)
                .HasComment("Pontos gerados para o parceiro nesta compra.")
                .HasColumnName("pontos_gerados_parceiro");
            entity.Property(e => e.RegistradoPor)
                .HasComment("Funcionário ou Administrador que lançou a compra.")
                .HasColumnName("registrado_por");
            entity.Property(e => e.Valor)
                .HasPrecision(12, 2)
                .HasColumnName("valor");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Compras)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_compras_cliente");

            entity.HasOne(d => d.Parceiro).WithMany(p => p.Compras)
                .HasForeignKey(d => d.ParceiroId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_compras_parceiro");

            entity.HasOne(d => d.RegistradoPorNavigation).WithMany(p => p.Compras)
                .HasForeignKey(d => d.RegistradoPor)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_compras_registrado_por");
        });

        modelBuilder.Entity<ComprasFuncionarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("compras_funcionarios_pkey");

            entity.ToTable("compras_funcionarios", tb => tb.HasComment("Registro de compras internas realizadas por funcionários (apenas para controle, sem gerar pontos)."));

            entity.HasIndex(e => e.DataCompra, "ix_compras_func_data").IsDescending();

            entity.HasIndex(e => e.FuncionarioId, "ix_compras_func_funcionario");

            entity.HasIndex(e => e.RegistradoPor, "ix_compras_func_registrado");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.DataCompra)
                .HasDefaultValueSql("now()")
                .HasColumnName("data_compra");
            entity.Property(e => e.Descricao)
                .HasMaxLength(500)
                .HasComment("Descrição opcional dos itens comprados.")
                .HasColumnName("descricao");
            entity.Property(e => e.FuncionarioId).HasColumnName("funcionario_id");
            entity.Property(e => e.RegistradoPor)
                .HasComment("Usuário (Admin ou Funcionario) que registrou a compra.")
                .HasColumnName("registrado_por");
            entity.Property(e => e.Valor)
                .HasPrecision(12, 2)
                .HasComment("Valor total da compra.")
                .HasColumnName("valor");

            entity.HasOne(d => d.Funcionario).WithMany(p => p.ComprasFuncionarios)
                .HasForeignKey(d => d.FuncionarioId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_compras_func_funcionario");

            entity.HasOne(d => d.RegistradoPorNavigation).WithMany(p => p.ComprasFuncionarios)
                .HasForeignKey(d => d.RegistradoPor)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_compras_func_registrado_por");
        });

        modelBuilder.Entity<ExtratoPontos>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("extrato_pontos_pkey");

            entity.ToTable("extrato_pontos", tb => tb.HasComment("Ledger imutável — registra toda movimentação de pontos (geração e resgate)."));

            entity.HasIndex(e => e.ClienteId, "ix_extrato_cliente").HasFilter("(cliente_id IS NOT NULL)");

            entity.HasIndex(e => e.CompraId, "ix_extrato_compra").HasFilter("(compra_id IS NOT NULL)");

            entity.HasIndex(e => e.CriadoEm, "ix_extrato_criado_em").IsDescending();

            entity.HasIndex(e => e.ParceiroId, "ix_extrato_parceiro");

            entity.HasIndex(e => e.TipoTransacao, "ix_extrato_tipo_transacao");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.ClienteId).HasColumnName("cliente_id");
            entity.Property(e => e.CompraId)
                .HasComment("Compra que originou os pontos (NULL para resgates).")
                .HasColumnName("compra_id");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.Descricao)
                .HasMaxLength(500)
                .HasColumnName("descricao");
            entity.Property(e => e.ParceiroId).HasColumnName("parceiro_id");
            entity.Property(e => e.Pontos).HasColumnName("pontos");
            entity.Property(e => e.TipoTransacao)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Tipo: Ganho (gerado por compra) ou Resgate (resgate pelo parceiro).")
                .HasColumnName("tipo_transacao");
            entity.Property(e => e.ValorMonetario)
                .HasPrecision(12, 2)
                .HasComment("Valor em R$ equivalente aos pontos (para resgates).")
                .HasColumnName("valor_monetario");

            entity.HasOne(d => d.Cliente).WithMany(p => p.ExtratoPontos)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_extrato_cliente");

            entity.HasOne(d => d.Compra).WithMany(p => p.ExtratoPontos)
                .HasForeignKey(d => d.CompraId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_extrato_compra");

            entity.HasOne(d => d.Parceiro).WithMany(p => p.ExtratoPontos)
                .HasForeignKey(d => d.ParceiroId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_extrato_parceiro");
        });

        modelBuilder.Entity<Funcionarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("funcionarios_pkey");

            entity.ToTable("funcionarios", tb => tb.HasComment("Dados complementares do Funcionario (vinculado ao usuario)."));

            entity.HasIndex(e => e.UsuarioId, "uq_funcionarios_usuario").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.UsuarioId).HasColumnName("usuario_id");

            entity.HasOne(d => d.Usuario).WithOne(p => p.Funcionarios)
                .HasForeignKey<Funcionarios>(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_funcionarios_usuario");
        });

        modelBuilder.Entity<Parceiros>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("parceiros_pkey");

            entity.ToTable("parceiros", tb => tb.HasComment("Dados complementares do Parceiro — saldo de pontos acumulado."));

            entity.HasIndex(e => e.UsuarioId, "uq_parceiros_usuario").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.TotalPontos)
                .HasComment("Saldo atual de pontos do parceiro (ganhos - resgates).")
                .HasColumnName("total_pontos");
            entity.Property(e => e.UsuarioId).HasColumnName("usuario_id");

            entity.HasOne(d => d.Usuario).WithOne(p => p.Parceiros)
                .HasForeignKey<Parceiros>(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_parceiros_usuario");
        });

        modelBuilder.Entity<RegrasPontuacao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("regras_pontuacao_pkey");

            entity.ToTable("regras_pontuacao", tb => tb.HasComment("Regras parametrizáveis de geração de pontos (configuradas pelo Administrador)."));

            entity.HasIndex(e => e.Ativo, "ix_regras_pontuacao_ativo").HasFilter("(ativo = true)");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.Ativo)
                .HasDefaultValue(true)
                .HasComment("Apenas uma regra ativa por vez — controlado por lógica de aplicação.")
                .HasColumnName("ativo");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.CriadoPor).HasColumnName("criado_por");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nome");
            entity.Property(e => e.PontosParaConversaoMonetariaCliente)
                .HasDefaultValue(100)
                .HasComment("Quantidade de pontos necessários para conversão monetária do cliente.")
                .HasColumnName("pontos_para_conversao_monetaria_cliente");
            entity.Property(e => e.PontosParaConversaoMonetariaParceiro)
                .HasComment("Quantidade de pontos necessários para conversão monetária (ex: 100 pontos).")
                .HasColumnName("pontos_para_conversao_monetaria_parceiro");
            entity.Property(e => e.PontosPorValorCliente)
                .HasDefaultValue(100)
                .HasComment("Quantidade de pontos gerados ao atingir o valor mínimo para o cliente.")
                .HasColumnName("pontos_por_valor_cliente");
            entity.Property(e => e.PontosPorValorParceiro)
                .HasComment("Quantidade de pontos gerados ao atingir o valor mínimo (ex: 100 pontos).")
                .HasColumnName("pontos_por_valor_parceiro");
            entity.Property(e => e.ValorCompraMinimoCliente)
                .HasPrecision(12, 2)
                .HasDefaultValue(1000.00m)
                .HasComment("Valor em R$ de compras necessário para gerar pontos para o cliente (ex: R$ 1.000,00).")
                .HasColumnName("valor_compra_minimo_cliente");
            entity.Property(e => e.ValorCompraMinimoParceiro)
                .HasPrecision(12, 2)
                .HasComment("Valor em R$ de compras necessário para gerar pontos (ex: R$ 1.000,00).")
                .HasColumnName("valor_compra_minimo_parceiro");
            entity.Property(e => e.ValorMonetarioPorPontosCliente)
                .HasPrecision(12, 2)
                .HasDefaultValue(50.00m)
                .HasComment("Valor em R$ que o cliente recebe ao resgatar pontos.")
                .HasColumnName("valor_monetario_por_pontos_cliente");
            entity.Property(e => e.ValorMonetarioPorPontosParceiro)
                .HasPrecision(12, 2)
                .HasComment("Valor em R$ que o parceiro recebe ao resgatar pontos (ex: R$ 50,00).")
                .HasColumnName("valor_monetario_por_pontos_parceiro");

            entity.HasOne(d => d.CriadoPorNavigation).WithMany(p => p.RegrasPontuacao)
                .HasForeignKey(d => d.CriadoPor)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_regras_pontuacao_criado_por");
        });

        modelBuilder.Entity<Resgates>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("resgates_pkey");

            entity.ToTable("resgates", tb => tb.HasComment("Solicitações de resgate de bônus pelos parceiros."));

            entity.HasIndex(e => e.ClienteId, "ix_resgates_cliente");

            entity.HasIndex(e => e.CriadoEm, "ix_resgates_criado_em").IsDescending();

            entity.HasIndex(e => e.ParceiroId, "ix_resgates_parceiro");

            entity.HasIndex(e => e.Status, "ix_resgates_status");

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.AprovadoPor)
                .HasComment("Administrador/Funcionário que aprovou o resgate.")
                .HasColumnName("aprovado_por");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.ClienteId).HasColumnName("cliente_id");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.Observacoes)
                .HasMaxLength(500)
                .HasColumnName("observacoes");
            entity.Property(e => e.ParceiroId).HasColumnName("parceiro_id");
            entity.Property(e => e.PontosResgatados).HasColumnName("pontos_resgatados");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("'Pendente'::character varying")
                .HasComment("Status do resgate: Pendente, Aprovado, Rejeitado, Cancelado.")
                .HasColumnName("status");
            entity.Property(e => e.ValorMonetario)
                .HasPrecision(12, 2)
                .HasColumnName("valor_monetario");

            entity.HasOne(d => d.AprovadoPorNavigation).WithMany(p => p.Resgates)
                .HasForeignKey(d => d.AprovadoPor)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_resgates_aprovado_por");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Resgates)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_resgates_cliente");

            entity.HasOne(d => d.Parceiro).WithMany(p => p.Resgates)
                .HasForeignKey(d => d.ParceiroId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("fk_resgates_parceiro");
        });

        modelBuilder.Entity<TokensAtualizacao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("tokens_atualizacao_pkey");

            entity.ToTable("tokens_atualizacao", tb => tb.HasComment("Tokens de refresh para renovação da autenticação JWT."));

            entity.HasIndex(e => e.ExpiraEm, "ix_tokens_atualizacao_expira_em");

            entity.HasIndex(e => e.UsuarioId, "ix_tokens_atualizacao_usuario");

            entity.HasIndex(e => e.Token, "uq_tokens_atualizacao_token").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.ExpiraEm).HasColumnName("expira_em");
            entity.Property(e => e.RevogadoEm)
                .HasComment("Data/hora da revogação — NULL enquanto ativo.")
                .HasColumnName("revogado_em");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasColumnName("token");
            entity.Property(e => e.UsuarioId).HasColumnName("usuario_id");

            entity.HasOne(d => d.Usuario).WithMany(p => p.TokensAtualizacao)
                .HasForeignKey(d => d.UsuarioId)
                .HasConstraintName("fk_tokens_atualizacao_usuario");
        });

        modelBuilder.Entity<Usuarios>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("usuarios_pkey");

            entity.ToTable("usuarios", tb => tb.HasComment("Tabela unificada de usuários do sistema (Administrador, Funcionario, Parceiro, Cliente)."));

            entity.HasIndex(e => e.Ativo, "ix_usuarios_ativo").HasFilter("(ativo = true)");

            entity.HasIndex(e => e.Email, "ix_usuarios_email").HasFilter("(email IS NOT NULL)");

            entity.HasIndex(e => e.Perfil, "ix_usuarios_perfil");

            entity.HasIndex(e => e.Email, "uq_usuarios_email").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("uuid_generate_v4()")
                .HasColumnName("id");
            entity.Property(e => e.Ativo)
                .HasDefaultValue(true)
                .HasColumnName("ativo");
            entity.Property(e => e.AtualizadoEm).HasColumnName("atualizado_em");
            entity.Property(e => e.CriadoEm)
                .HasDefaultValueSql("now()")
                .HasColumnName("criado_em");
            entity.Property(e => e.Email)
                .HasMaxLength(254)
                .HasColumnName("email");
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("nome");
            entity.Property(e => e.Perfil)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("Perfil de acesso: Administrador, Funcionario, Parceiro, Cliente.")
                .HasColumnName("perfil");
            entity.Property(e => e.SenhaHash)
                .IsRequired()
                .HasComment("Hash da senha gerado via bcrypt/Argon2.")
                .HasColumnName("senha_hash");
            entity.Property(e => e.Telefone)
                .HasMaxLength(20)
                .HasComment("Telefone/WhatsApp do usuário.")
                .HasColumnName("telefone");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}